### ISSUE TITLE
Relations allow inserting Records that follow a different schema than their own

### ISSUE THREAD

**Issue by srfc** [CodeLionX/actordb#10]
# Issue

If a `Record` that is built using a different schema (i.e. ColumnDef sequence) than some `Relation`, it can still be inserted into said `Relation`.

# Problem Description

If a `Record` that is built using a different schema (i.e. ColumnDef sequence) than some `Relation`, it can still be inserted into said `Relation`. All fields of the record, which do not correspond to a ColumnDef of the `Relation` are subsequently lost.

I propose adding a check on `Relation.insert` and `Relation.insertAll` if the `Record.columns` equal the `Relation.columns` and returning a Either[Error/InsertedRecord(s)]. **Would this be the proper way to add success/failure feedback?**

# Supporting Information

```scala
val R: RowRelation = RowRelation(Seq(ColumnDef[Int]("id"), ColumnDef[Int]("age")))

R.insert(
  Record(Seq(ColumnDef[Int]("zipcode"), ColumnDef[String]("lastname")))
    .withCellContent(ColumnDef[Int]("zipcode") -> 13357)
    .withCellContent(ColumnDef[String]("lastname") -> "Meyer")
    .build()
)
// DOES NOT FAIL
// results in a row with all Some(null) values in R
```

**Comment by CodeLionX** [comment]
I like your idea using `Either[T]` as return type. I just want to throw in the type `Try` of the scala standard library: 

> The `Try` type represents a computation that may either result in an exception, or return a successfully computed value. It's similar to, but semantically different from the `scala.util.Either` type.
>
> [scala-lang API](https://www.scala-lang.org/api/2.12.3/scala/util/Try.html)

**Comment by srfc** [comment]
I think this should fail. Ideally a user should always - in my mind at least - use the `Relation` he wants to insert data into to create new `Record`'s. I.e.

```scala
val result = R.insert(
  R.newRecord
    .withCellContent(ColumnDef[Int]("id") -> 12412)
    .withCellContent(ColumnDef[String]("name") -> "Max Mustermann")
    .build()
)
```

At least I would encourage this, or the `Record(R.columns)` pattern. On each `insert` I would check if the column layout of the `Record` fits the `Relation`'s.

Otherwise we will silently drop data that someone thinks they're pushing into the relation because they e.g. forgot to update the `Relation`'s column layout and that would be bad.

**Comment by CodeLionX** [comment]
Alright, I agree.

+1 for:
```scala
val r = R.newRecord.build()
```
