### ISSUE TITLE
Add Tests for Definitions

### ISSUE THREAD

**Issue by srfc** [CodeLionX/actordb#20]
# Issue

Add tests for all definition classes, objects, traits.

- [x] `ColumnDef[T]` and `UntypedColumnDef`
  - ensure `equals()` (and similar) and `hashCode()` work correctly
  - ensure `clone()` works correctly
  - demonstrate `ClassTag[T]` usage
- [ ] ~`ColumnRelation`~ (deprecated with #24)
- [x] `RowRelation`
- [x] `Record`

# Problem Description

We don't have tests yet.

# Supporting Information

n/a

**Comment by CodeLionX** [comment]
hint for `ColumnDef[T]#equals()` test: [asserts in `TestApplication`](https://github.com/CodeLionX/actordb/blob/master/sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala#L81)

**Comment by CodeLionX** [comment]
I guess this was fixed with #31 and #32. All following PRs should update corresponding tests!
