### ISSUE TITLE
Change return type of `Relation.insertAll` from `Unit` to `Try[Seq[Record]]`

### ISSUE THREAD

**Issue by srfc** [CodeLionX/actordb#34]
# Issue

The current return type of `Relation.insertAll` does not give any insight in whether or not the operation succeeded.

# Problem Description

- The current return type of `Relation.insertAll` does not give any insight in whether or not the operation succeeded.

- Change return type of `Relation.insertAll` from `Unit` to `Try[Seq[Record]]`

# Supporting Information

- Behaviour is then analogous to `Relation.insert`

**Comment by CodeLionX** [comment]
fixed with #31
