### ISSUE TITLE
[sampleapp] Add test (actor) to initialize a small DB and test some queries

### ISSUE THREAD

**Issue by srfc** [CodeLionX/actordb#52]
# Issue

Test inter-`Dactor` messaging and how to add contents to `Dactor`s.

# Problem Description

- Should be an `Actor` or `TestActor` itself
- Can be static content and queries for now

# Supporting Information

n/a

**Comment by CodeLionX** [comment]
Kind of already solved by #86 and #74:
- `SystemTest`
- `SystemInitializer` and `DataInitializer`

Should we close this?

**Comment by srfc** [comment]
Yes.
