### ISSUE TITLE
Add tests to `Dactor` for `askDactor`

### ISSUE THREAD

**Issue by srfc** [CodeLionX/actordb#76]
# Issue

We are missing a test for the `askDactor` method of the `Dactor` c.o.

# Problem Description

- only implicitely tested in `sampleapp` through `Dactor` implementations, there we only test success cases
- failed `askDactor` calls are never tested

# Supporting Information

**Comment by srfc** [comment]
API deprecated. Let's close this.

**Comment by CodeLionX** [comment]
obsolete
